// require('./model.test.js')
// require('./reducerTests/movesReducer.test.js')
require('./reducerTests/fallingMagnitudeReducer.test.js')
// require('./reducerTests/isLeavingReducer.test.js')
// require('./reducerTests/boardReducer.test.js')
